# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ControllerAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.DelegateCall", "types.GenerateReportCall", "types.SendTelegramCall", "types.SendToNotionCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ControllerAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.DelegateCall", "types.GenerateReportCall", "types.SendTelegramCall", "types.SendToNotionCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    def MonitorAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.FetchPortfoliosCall", "types.DetectAlertsCall", "types.FetchPriceHistoryCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MonitorAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.FetchPortfoliosCall", "types.DetectAlertsCall", "types.FetchPriceHistoryCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    def NewsAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.FetchNewsCall", "types.AnalyzeSentimentCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="NewsAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.FetchNewsCall", "types.AnalyzeSentimentCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    def RebalancerAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.GetCurrentAllocationCall", "types.GetTargetAllocationCall", "types.CalculateRebalanceCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RebalancerAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.GetCurrentAllocationCall", "types.GetTargetAllocationCall", "types.CalculateRebalanceCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    def TaxAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.GetTransactionHistoryCall", "types.CalculateTaxCall", "types.GetTaxOptimizationTipsCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TaxAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.GetTransactionHistoryCall", "types.CalculateTaxCall", "types.GetTaxOptimizationTipsCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    def TraderAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CheckLiquidityCall", "types.SimulateSwapCall", "types.GetOptimalRouteCall", "types.AskHumanCall", "types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TraderAgentStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CheckLiquidityCall", "types.SimulateSwapCall", "types.GetOptimalRouteCall", "types.AskHumanCall", "types.DoneCall"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ControllerAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.DelegateCall", "stream_types.GenerateReportCall", "stream_types.SendTelegramCall", "stream_types.SendToNotionCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ControllerAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.DelegateCall", "stream_types.GenerateReportCall", "stream_types.SendTelegramCall", "stream_types.SendToNotionCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    def MonitorAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.FetchPortfoliosCall", "stream_types.DetectAlertsCall", "stream_types.FetchPriceHistoryCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MonitorAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.FetchPortfoliosCall", "stream_types.DetectAlertsCall", "stream_types.FetchPriceHistoryCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    def NewsAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.FetchNewsCall", "stream_types.AnalyzeSentimentCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="NewsAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.FetchNewsCall", "stream_types.AnalyzeSentimentCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    def RebalancerAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.GetCurrentAllocationCall", "stream_types.GetTargetAllocationCall", "stream_types.CalculateRebalanceCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RebalancerAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.GetCurrentAllocationCall", "stream_types.GetTargetAllocationCall", "stream_types.CalculateRebalanceCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    def TaxAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.GetTransactionHistoryCall", "stream_types.CalculateTaxCall", "stream_types.GetTaxOptimizationTipsCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TaxAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.GetTransactionHistoryCall", "stream_types.CalculateTaxCall", "stream_types.GetTaxOptimizationTipsCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    def TraderAgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CheckLiquidityCall", "stream_types.SimulateSwapCall", "stream_types.GetOptimalRouteCall", "stream_types.AskHumanCall", "stream_types.DoneCall"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TraderAgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CheckLiquidityCall", "stream_types.SimulateSwapCall", "stream_types.GetOptimalRouteCall", "stream_types.AskHumanCall", "stream_types.DoneCall"], __result__)

    