# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (20)
# #########################################################################

class AnalyzeSentimentCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['analyze_sentiment']] = None
    reason: typing.Optional[str] = None

class AskHumanCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['ask_human']] = None
    level: typing.Optional[typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['critical']]] = None
    question: typing.Optional[str] = Field(default=None, description='사람에게 묻는 질문')
    context: typing.Optional[str] = Field(default=None, description='추가 컨텍스트 (선택)')
    reason: typing.Optional[str] = None

class CalculateRebalanceCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['calculate_rebalance']] = None
    reason: typing.Optional[str] = None

class CalculateTaxCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['calculate_tax']] = None
    jurisdiction: typing.Optional[str] = Field(default=None, description='세금 관할권 코드 (예: KR)')
    reason: typing.Optional[str] = None

class CheckLiquidityCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['check_liquidity']] = None
    pair: typing.Optional[str] = Field(default=None, description='거래쌍 (예: FXRP/FLR)')
    reason: typing.Optional[str] = None

class DelegateCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['delegate']] = None
    agent: typing.Optional[typing.Union[typing_extensions.Literal['monitor'], typing_extensions.Literal['news'], typing_extensions.Literal['trader'], typing_extensions.Literal['rebalancer'], typing_extensions.Literal['tax']]] = Field(default=None, description='위임할 Sub-Agent 이름')
    task: typing.Optional[str] = Field(default=None, description='Sub-Agent에게 전달할 구체적 작업 지시')
    reason: typing.Optional[str] = None

class DetectAlertsCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['detect_alerts']] = None
    reason: typing.Optional[str] = None

class DoneCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['done']] = None
    summary: typing.Optional[str] = Field(default=None, description='작업 완료 요약')
    reason: typing.Optional[str] = None

class FetchNewsCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['fetch_news']] = None
    chain: typing.Optional[typing.Union[typing_extensions.Literal['Flare'], typing_extensions.Literal['XDC'], typing_extensions.Literal['all']]] = Field(default=None, description='조회할 체인')
    reason: typing.Optional[str] = None

class FetchPortfoliosCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['fetch_portfolios']] = None
    reason: typing.Optional[str] = None

class FetchPriceHistoryCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['fetch_price_history']] = None
    asset: typing.Optional[typing.Union[typing_extensions.Literal['FLR'], typing_extensions.Literal['XDC'], typing_extensions.Literal['XRP']]] = Field(default=None, description='조회할 자산 심볼')
    days: typing.Optional[int] = Field(default=None, description='조회할 일수 (기본 7일)')
    reason: typing.Optional[str] = None

class GenerateReportCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['generate_report']] = None
    type: typing.Optional[typing.Union[typing_extensions.Literal['daily'], typing_extensions.Literal['weekly'], typing_extensions.Literal['alert']]] = Field(default=None, description='리포트 종류')
    reason: typing.Optional[str] = None

class GetCurrentAllocationCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['get_current_allocation']] = None
    reason: typing.Optional[str] = None

class GetOptimalRouteCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['get_optimal_route']] = None
    reason: typing.Optional[str] = None

class GetTargetAllocationCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['get_target_allocation']] = None
    strategy: typing.Optional[typing.Union[typing_extensions.Literal['balanced'], typing_extensions.Literal['aggressive'], typing_extensions.Literal['conservative']]] = Field(default=None, description='리밸런싱 전략')
    reason: typing.Optional[str] = None

class GetTaxOptimizationTipsCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['get_tax_optimization_tips']] = None
    reason: typing.Optional[str] = None

class GetTransactionHistoryCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['get_transaction_history']] = None
    period: typing.Optional[str] = Field(default=None, description='조회 기간 (예: 2025)')
    reason: typing.Optional[str] = None

class SendTelegramCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['send_telegram_alert']] = None
    message: typing.Optional[str] = Field(default=None, description='전송할 메시지 내용')
    level: typing.Optional[typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['critical']]] = Field(default=None, description='알림 수준')
    reason: typing.Optional[str] = None

class SendToNotionCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['send_to_notion']] = None
    report_id: typing.Optional[str] = Field(default=None, description='저장할 리포트 ID')
    reason: typing.Optional[str] = None

class SimulateSwapCall(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['simulate_swap']] = None
    from_asset: typing.Optional[str] = Field(default=None, description='소스 자산 심볼 (예: FLR)')
    to_asset: typing.Optional[str] = Field(default=None, description='대상 자산 심볼 (예: FXRP)')
    amount: typing.Optional[float] = Field(default=None, description='스왑 수량')
    reason: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (6)
# #########################################################################


ControllerToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["DelegateCall", "GenerateReportCall", "SendTelegramCall", "SendToNotionCall", "AskHumanCall", "DoneCall"]]


MonitorToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["FetchPortfoliosCall", "DetectAlertsCall", "FetchPriceHistoryCall", "AskHumanCall", "DoneCall"]]


NewsToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["FetchNewsCall", "AnalyzeSentimentCall", "AskHumanCall", "DoneCall"]]


RebalancerToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["GetCurrentAllocationCall", "GetTargetAllocationCall", "CalculateRebalanceCall", "AskHumanCall", "DoneCall"]]


TaxToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["GetTransactionHistoryCall", "CalculateTaxCall", "GetTaxOptimizationTipsCall", "AskHumanCall", "DoneCall"]]


TraderToolCall: typing_extensions.TypeAlias = typing.Optional[typing.Union["CheckLiquidityCall", "SimulateSwapCall", "GetOptimalRouteCall", "AskHumanCall", "DoneCall"]]
