# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnalyzeSentimentCall": types.AnalyzeSentimentCall,
    "stream_types.AnalyzeSentimentCall": stream_types.AnalyzeSentimentCall,

    "types.AskHumanCall": types.AskHumanCall,
    "stream_types.AskHumanCall": stream_types.AskHumanCall,

    "types.CalculateRebalanceCall": types.CalculateRebalanceCall,
    "stream_types.CalculateRebalanceCall": stream_types.CalculateRebalanceCall,

    "types.CalculateTaxCall": types.CalculateTaxCall,
    "stream_types.CalculateTaxCall": stream_types.CalculateTaxCall,

    "types.CheckLiquidityCall": types.CheckLiquidityCall,
    "stream_types.CheckLiquidityCall": stream_types.CheckLiquidityCall,

    "types.DelegateCall": types.DelegateCall,
    "stream_types.DelegateCall": stream_types.DelegateCall,

    "types.DetectAlertsCall": types.DetectAlertsCall,
    "stream_types.DetectAlertsCall": stream_types.DetectAlertsCall,

    "types.DoneCall": types.DoneCall,
    "stream_types.DoneCall": stream_types.DoneCall,

    "types.FetchNewsCall": types.FetchNewsCall,
    "stream_types.FetchNewsCall": stream_types.FetchNewsCall,

    "types.FetchPortfoliosCall": types.FetchPortfoliosCall,
    "stream_types.FetchPortfoliosCall": stream_types.FetchPortfoliosCall,

    "types.FetchPriceHistoryCall": types.FetchPriceHistoryCall,
    "stream_types.FetchPriceHistoryCall": stream_types.FetchPriceHistoryCall,

    "types.GenerateReportCall": types.GenerateReportCall,
    "stream_types.GenerateReportCall": stream_types.GenerateReportCall,

    "types.GetCurrentAllocationCall": types.GetCurrentAllocationCall,
    "stream_types.GetCurrentAllocationCall": stream_types.GetCurrentAllocationCall,

    "types.GetOptimalRouteCall": types.GetOptimalRouteCall,
    "stream_types.GetOptimalRouteCall": stream_types.GetOptimalRouteCall,

    "types.GetTargetAllocationCall": types.GetTargetAllocationCall,
    "stream_types.GetTargetAllocationCall": stream_types.GetTargetAllocationCall,

    "types.GetTaxOptimizationTipsCall": types.GetTaxOptimizationTipsCall,
    "stream_types.GetTaxOptimizationTipsCall": stream_types.GetTaxOptimizationTipsCall,

    "types.GetTransactionHistoryCall": types.GetTransactionHistoryCall,
    "stream_types.GetTransactionHistoryCall": stream_types.GetTransactionHistoryCall,

    "types.SendTelegramCall": types.SendTelegramCall,
    "stream_types.SendTelegramCall": stream_types.SendTelegramCall,

    "types.SendToNotionCall": types.SendToNotionCall,
    "stream_types.SendToNotionCall": stream_types.SendToNotionCall,

    "types.SimulateSwapCall": types.SimulateSwapCall,
    "stream_types.SimulateSwapCall": stream_types.SimulateSwapCall,


}