# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (20)
# #########################################################################

class AnalyzeSentimentCall(BaseModel):
    tool: typing_extensions.Literal['analyze_sentiment']
    reason: str

class AskHumanCall(BaseModel):
    tool: typing_extensions.Literal['ask_human']
    level: typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['critical']]
    question: str = Field(description='사람에게 묻는 질문')
    context: typing.Optional[str] = Field(default=None, description='추가 컨텍스트 (선택)')
    reason: str

class CalculateRebalanceCall(BaseModel):
    tool: typing_extensions.Literal['calculate_rebalance']
    reason: str

class CalculateTaxCall(BaseModel):
    tool: typing_extensions.Literal['calculate_tax']
    jurisdiction: str = Field(description='세금 관할권 코드 (예: KR)')
    reason: str

class CheckLiquidityCall(BaseModel):
    tool: typing_extensions.Literal['check_liquidity']
    pair: str = Field(description='거래쌍 (예: FXRP/FLR)')
    reason: str

class DelegateCall(BaseModel):
    tool: typing_extensions.Literal['delegate']
    agent: typing.Union[typing_extensions.Literal['monitor'], typing_extensions.Literal['news'], typing_extensions.Literal['trader'], typing_extensions.Literal['rebalancer'], typing_extensions.Literal['tax']] = Field(description='위임할 Sub-Agent 이름')
    task: str = Field(description='Sub-Agent에게 전달할 구체적 작업 지시')
    reason: str

class DetectAlertsCall(BaseModel):
    tool: typing_extensions.Literal['detect_alerts']
    reason: str

class DoneCall(BaseModel):
    tool: typing_extensions.Literal['done']
    summary: str = Field(description='작업 완료 요약')
    reason: str

class FetchNewsCall(BaseModel):
    tool: typing_extensions.Literal['fetch_news']
    chain: typing.Union[typing_extensions.Literal['Flare'], typing_extensions.Literal['XDC'], typing_extensions.Literal['all']] = Field(description='조회할 체인')
    reason: str

class FetchPortfoliosCall(BaseModel):
    tool: typing_extensions.Literal['fetch_portfolios']
    reason: str

class FetchPriceHistoryCall(BaseModel):
    tool: typing_extensions.Literal['fetch_price_history']
    asset: typing.Union[typing_extensions.Literal['FLR'], typing_extensions.Literal['XDC'], typing_extensions.Literal['XRP']] = Field(description='조회할 자산 심볼')
    days: int = Field(description='조회할 일수 (기본 7일)')
    reason: str

class GenerateReportCall(BaseModel):
    tool: typing_extensions.Literal['generate_report']
    type: typing.Union[typing_extensions.Literal['daily'], typing_extensions.Literal['weekly'], typing_extensions.Literal['alert']] = Field(description='리포트 종류')
    reason: str

class GetCurrentAllocationCall(BaseModel):
    tool: typing_extensions.Literal['get_current_allocation']
    reason: str

class GetOptimalRouteCall(BaseModel):
    tool: typing_extensions.Literal['get_optimal_route']
    reason: str

class GetTargetAllocationCall(BaseModel):
    tool: typing_extensions.Literal['get_target_allocation']
    strategy: typing.Union[typing_extensions.Literal['balanced'], typing_extensions.Literal['aggressive'], typing_extensions.Literal['conservative']] = Field(description='리밸런싱 전략')
    reason: str

class GetTaxOptimizationTipsCall(BaseModel):
    tool: typing_extensions.Literal['get_tax_optimization_tips']
    reason: str

class GetTransactionHistoryCall(BaseModel):
    tool: typing_extensions.Literal['get_transaction_history']
    period: str = Field(description='조회 기간 (예: 2025)')
    reason: str

class SendTelegramCall(BaseModel):
    tool: typing_extensions.Literal['send_telegram_alert']
    message: str = Field(description='전송할 메시지 내용')
    level: typing.Union[typing_extensions.Literal['info'], typing_extensions.Literal['warning'], typing_extensions.Literal['critical']] = Field(description='알림 수준')
    reason: str

class SendToNotionCall(BaseModel):
    tool: typing_extensions.Literal['send_to_notion']
    report_id: str = Field(description='저장할 리포트 ID')
    reason: str

class SimulateSwapCall(BaseModel):
    tool: typing_extensions.Literal['simulate_swap']
    from_asset: str = Field(description='소스 자산 심볼 (예: FLR)')
    to_asset: str = Field(description='대상 자산 심볼 (예: FXRP)')
    amount: float = Field(description='스왑 수량')
    reason: str

# #########################################################################
# Generated type aliases (6)
# #########################################################################


ControllerToolCall: typing_extensions.TypeAlias = typing.Union["DelegateCall", "GenerateReportCall", "SendTelegramCall", "SendToNotionCall", "AskHumanCall", "DoneCall"]


MonitorToolCall: typing_extensions.TypeAlias = typing.Union["FetchPortfoliosCall", "DetectAlertsCall", "FetchPriceHistoryCall", "AskHumanCall", "DoneCall"]


NewsToolCall: typing_extensions.TypeAlias = typing.Union["FetchNewsCall", "AnalyzeSentimentCall", "AskHumanCall", "DoneCall"]


RebalancerToolCall: typing_extensions.TypeAlias = typing.Union["GetCurrentAllocationCall", "GetTargetAllocationCall", "CalculateRebalanceCall", "AskHumanCall", "DoneCall"]


TaxToolCall: typing_extensions.TypeAlias = typing.Union["GetTransactionHistoryCall", "CalculateTaxCall", "GetTaxOptimizationTipsCall", "AskHumanCall", "DoneCall"]


TraderToolCall: typing_extensions.TypeAlias = typing.Union["CheckLiquidityCall", "SimulateSwapCall", "GetOptimalRouteCall", "AskHumanCall", "DoneCall"]
